### PR TITLE
Issue 618 - Keyboard navigation in sparsely readonly table

### LINKED ISSUE #618: Can't navigate with keyboard through non-editable cells
Using the standalone app (for simplicity, will be the same with callbacks).
Not sure when this regression appeared, probably `<=1.0.0`.

Modify `eee` and `fff` columns in `data.ts` with

```
editable: false
```

Navigating with the keyboard, upon reaching columns `eee` or `fff`, won't be able to move from the cell afterwards.

### PR DESCRIPTION
**Pull request by Marc-Andre-Rivet**
Fixes #618 

New test, failure prior to fix: https://circleci.com/gh/plotly/dash-table/14271
Passes after fix: https://circleci.com/gh/plotly/dash-table/14278

### CODE REVIEW

File: src/dash-table/components/CellLabel/index.tsx [hunk 1]
```diff
@@ -15,11 +16,34 @@ export default class CellLabel extends PureComponent<IProps> {
         } = this.props;
 
         return (<div
+            ref='el'
             className={className}
+            tabIndex={-1}
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/CellLabel/index.tsx]: this makes the element focusable

File: package-lock.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "dash-table",
-  "version": "4.3.0",
+  "version": "4.4.0",
```
Comment (alexcjohnson) [inline package-lock.json]: 🙈

File: src/dash-table/components/CellLabel/index.tsx (hunk 1 above)
Comment (alexcjohnson) [reply src/dash-table/components/CellLabel/index.tsx]: neat, I didn't know about that
https://webaim.org/techniques/keyboard/tabindex

> A tabindex="-1" value removes the element from the default navigation flow and also allows it to receive programmatic focus.

Seems like the right call (as opposed to 0, keeping it in the tab "navigation flow")
