### PR TITLE
Page numbers and page navigation improvements

### LINKED ISSUE #299: show page numbers for pagination
Thanks for your interest in Plotly's Dash DataTable component!!

Note that GitHub issues in this repo are reserved for bug reports and feature
requests. Implementation questions should be discussed in our
[Dash Community Forum](https://community.plot.ly/c/dash).

Before opening a new issue, please search through existing issues (including
closed issues) and the [Dash Community Forum](https://community.plot.ly/c/dash).
If your problem or idea has not been addressed yet, feel free to
[open an issue](https://github.com/plotly/plotly.py/issues/new).

When reporting a bug, please include a reproducible example! We recommend using
the [latest version](https://github.com/plotly/dash-table/blob/master/CHANGELOG.md)
as this project is frequently updated. Issues can be browser-specific so
it's usually helpful to mention the browser and version that you are using.

Thanks for taking the time to help up improve this component!

### LINKED ISSUE #580: [FEATURE] Enhanced page navigation UI
The current paging UI only includes `Previous` and `Next` buttons. For large tables, it would be very helpful for the users to also have `First` and `Last`, display the (read-only) total number of pages, and the current page number (editable to allow navigating to a specific page).

Something like the classic 6-field paging UI: ⏪◀ `17` / 30 ▶⏩

### PR DESCRIPTION
**Pull request by shammamah**
Closes #580.
Closes #299.

## About 
* Updated appearance of previous/next buttons
* Added go-to-first and go-to-last buttons
* Added `{current}/{total}` page numbers between navigation arrows 
* Added support for user input to directly navigate to a page
* Moved pagination menu/functionality to separate component

### CODE REVIEW

File: src/dash-table/components/Table/props.ts [hunk 1]
```diff
@@ -318,6 +318,7 @@ export interface IProps {
     style_as_list_view?: boolean;
     page_action?: TableAction;
     page_current?: number;
+    max_page_count?: number | undefined;
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/Table/props.ts]:
```suggestion
    max_page_count?: number;
```

File: src/dash-table/dash/DataTable.js [hunk 2]
```diff
@@ -731,6 +731,14 @@ export const propTypes = {
      */
     page_current: PropTypes.number,
 
+    /**
+     * `max_page_count` represents the number of the last page of the
+     * paginated table. This is really only useful when performing
+     * backend pagination, since the front end is able to use the
+     * full size of the table to calculate the max page number.
+     */
+    max_page_count: PropTypes.number,
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/dash/DataTable.js]: Maybe `page_count` instead?

File: src/dash-table/components/ControlledTable/index.tsx [hunk 3]
```diff
@@ -858,10 +886,52 @@ export default class ControlledTable extends PureComponent<ControlledTableProps>
                     </div>))}
                 </div>
             </div>
-            {!this.displayPagination ? null : (
-                <div>
-                    <button className='previous-page' onClick={this.loadPrevious}>Previous</button>
-                    <button className='next-page' onClick={this.loadNext}>Next</button>
+            {!this.displayPagination || lastPage === 0 ? null : (
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/ControlledTable/index.tsx]: I think the page navigation is getting complex enough to warrant its own component at this point.

File: src/dash-table/components/ControlledTable/index.tsx [hunk 4]
```diff
@@ -641,6 +643,30 @@ export default class ControlledTable extends PureComponent<ControlledTableProps>
...
+    lastPage = () => {
+        const { paginator } = this.props;
+
+        return paginator.lastPage;
+    }
+
+    goToPage = (page_number: string) => {
+        const { paginator } = this.props;
+
+        paginator.goToPage(page_number);
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/ControlledTable/index.tsx]: Do the string -> number cast here instead to keep the paginator isolated from the UI details

File: src/dash-table/derived/paginator.ts [hunk 5]
```diff
@@ -19,8 +23,15 @@ export function lastPage(data: Data, page_size: number) {
...
 function getBackEndPagination(
     page_current: number,
-    setProps: SetProps
+    setProps: SetProps,
+    max_page_count: number | undefined
 ): IPaginator {
+
+    // adjust for zero-indexing
+    if (max_page_count) {
+        max_page_count = Math.max(0, max_page_count - 1);
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/derived/paginator.ts]: Should be able to handle an unknown `max_page_count` as this is a valid scenario. If not provided, could be `NaN` or `null` and prevent the use of `loadLast` for example. `max_page_count` prop should make it clear that the `null` case with BE with make some assumptions / deprecate the page navigation UI.

File: src/dash-table/derived/paginator.ts [hunk 6]
```diff
@@ -33,6 +44,43 @@ function getBackEndPagination(
...
+            if (isNaN(page)) {
+                return;
+            }
+
+            // adjust for zero-indexing
+            page--;
+
+            if (page < 0) {
+                page_current = 0;
+                setProps({ page_current, ...clearSelection });
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/derived/paginator.ts]: 🌴Maybe a function to call setProps within this closure to do ```page_current => setProps({ page_current, ...clearSelection });```

File: src/dash-table/derived/paginator.ts [hunk 7]
```diff
@@ -61,21 +109,60 @@ function getFrontEndPagination(
...
 
 function getNoPagination() {
     return {
         loadNext: () => { },
-        loadPrevious: () => { }
+        loadPrevious: () => { },
+        loadFirst: () => { },
+        loadLast: () => { },
+        lastPage: 0,
+        goToPage: () => { }
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/derived/paginator.ts]: The paginator could be responsible for determining the values used to enable/disable the UI: hasPrevious, hasNext, hasLast, keeping all the pagination logic together instead of separating it between the helper and the UI.

File: src/dash-table/derived/paginator.ts (hunk 5 above)
Comment (shammamah) [reply src/dash-table/derived/paginator.ts]: I'm doing that in the actual button: https://github.com/plotly/dash-table/blob/f1d90daeea6129b0dd8b8ac8816074175f8a3a4b/src/dash-table/components/ControlledTable/index.tsx#L932

I can move it into the paginator if that's better, though.

Comment (Marc-Andre-Rivet) [reply src/dash-table/derived/paginator.ts]: Yes please 🙏

File: src/dash-table/components/Table/Table.less [hunk 8]
```diff
@@ -140,6 +140,69 @@
...
+    border: none;
+}
+
+button.previous-page:hover, button.next-page:hover, button.first-page:hover, button.last-page:hover {
+    color: hotpink;
+}
+button.previous-page:hover:disabled, button.next-page:hover:disabled, button.first-page:hover:disabled, button.last-page:hover:disabled {
+    color: graytext
+}
+
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/Table/Table.less]: I suggest adding a class on the parent `div` at https://github.com/plotly/dash-table/blob/dev/src/dash-table/components/ControlledTable/index.tsx#L821 and using that class to wrap both the pagination styling and the `.dash-spreadsheet-container` below to prevent leaking styles outside the table's scope.

File: src/dash-table/components/PageNavigation/index.tsx [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+        const {
+            paginator,
+            page_current
+        } = this.props;
+
+        return (paginator.lastPage === 0 ? null : (
+            <div className='previous-next-container'>
+                <button
+                    className='first-page'
+                    onClick={this.loadFirst}
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/PageNavigation/index.tsx]: No need for a wrapper function, just use it directly:
```suggestion
                    onClick={this.props.paginator.loadFirst}
```

File: src/dash-table/components/PageNavigation/index.tsx [hunk 10]
```diff
@@ -0,0 +1,98 @@
...
+                    disabled={paginator.disablePrevious()}>
+                    <FontAwesomeIcon icon='angle-double-left' />
+                </button>
+
+                <button
+                    className='previous-page'
+                    onClick={this.loadPrevious}
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/PageNavigation/index.tsx]: idem

File: src/dash-table/components/PageNavigation/index.tsx [hunk 11]
```diff
@@ -0,0 +1,98 @@
...
+                    {paginator.lastPage ? ' / ' : ''}
+
+                    {paginator.lastPage ? <div className='last-page'>
+                        {paginator.lastPage ? paginator.lastPage + 1 : ''}
+                    </div> : ''}
+                </div>
+
+                <button
+                    className='next-page'
+                    onClick={this.loadNext}
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/PageNavigation/index.tsx]: idem

File: src/dash-table/components/PageNavigation/index.tsx [hunk 12]
```diff
@@ -0,0 +1,98 @@
...
+                    disabled={paginator.disableNext()} >
+                    <FontAwesomeIcon icon='angle-right' />
+                </button>
+
+                <button
+                    className='last-page'
+                    onClick={this.loadLast}
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/PageNavigation/index.tsx]: idem

File: src/dash-table/dash/DataTable.js [hunk 13]
```diff
@@ -731,6 +731,14 @@ export const propTypes = {
      */
     page_current: PropTypes.number,
 
+    /**
+     * `page_count` represents the number of the last page of the
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/dash/DataTable.js]: I understand page_count to be the number of pages of data in the table.
`the number of the last page` would be more like `page_max_index` (or page_count - 1), no?

```suggestion
     * `page_count` represents the number of the pages in the
```

File: src/dash-table/derived/paginator.ts [hunk 14]
```diff
@@ -33,6 +47,43 @@ function getBackEndPagination(
...
+            setProps({ page_current, ...clearSelection });
+        },
+        disablePrevious: () => {
+            return page_current === 0;
+        },
+        disableNext: () => {
+            return page_count !== undefined && page_current === page_count;
+        },
+        disableLast: () => {
+            return !page_count ? true : page_current === page_count;
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/derived/paginator.ts]: 🌴`getFrontEndPagination` and `getBackEndPagination` seem to share a significant amount of logic

File: src/dash-table/derived/paginator.ts [hunk 15]
```diff
@@ -11,6 +11,13 @@ import {
 export interface IPaginator {
     loadNext(): void;
     loadPrevious(): void;
+    loadFirst(): void;
+    loadLast(): void;
+    lastPage: number | undefined;
+    goToPage(page: number): void;
+    disablePrevious(): boolean;
+    disableNext(): boolean;
+    disableLast(): boolean;
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/derived/paginator.ts]: Non-blocking. `disablePrevious` is of form `action-noun` which typically indicates a modification will be made. `hasPrevious` is better as you are retrieving the value of some calculated state.

**Comment by shammamah** [comment]
@Marc-Andre-Rivet The gray underline came from a discussion with @alexcjohnson -- the purpose is to make it more obvious that the page number can be used as text input.

**Comment by alexcjohnson** [comment]
The gray underline looks nice to me - good call @shammamah. I presume if users want a different color, full border, or background color etc they can do it with the `css` prop?

**Comment by Marc-Andre-Rivet** [comment]
> I presume if users want a different color, full border, or background color etc they can do it with the css prop?

Yes

**Comment by Marc-Andre-Rivet** [comment]
FE & BE (w/ and w/o page_count) seems good.

Came across this unrelated issue: seeing **really weird** visual artifacts when switching page, getting misaligned rows and mismatched cell heights seemingly at random

image

Opened an issue for it here: https://github.com/plotly/dash-table/issues/607
