### PR TITLE
Issue 524 - Readonly dropdown column content

### LINKED ISSUE #524: Dropdown columns show their value and not their label when editable=False
If a table has a column that allows a user to edit the options from a dropdown but after a callback is fired that switches a column to being non-editable, the "value" from the column is displayed instead of the "label".

Peek 2019-08-01 17-36

```
import dash
from dash.dependencies import Input, Output, State
import dash_html_components as html
import dash_table
import pandas as pd
from collections import OrderedDict


app = dash.Dash(__name__)

df = pd.DataFrame(OrderedDict([
    ('climate', ['Sunny', 'Snowy', 'Sunny', 'Rainy']),
    ('temperature', [13, 43, 50, 30]),
    ('city', ['NYC', 'Montreal', 'Miami', 'NYC'])
]))


app.layout = html.Div([
    dash_table.DataTable(
        id='table-dropdown',
        data=df.to_dict('records'),
        columns=[
            {'id': 'climate', 'name': 'climate', 'presentation': 'dropdown', 'editable': False},
            {'id': 'temperature', 'name': 'temperature'},
            {'id': 'city', 'name': 'city', 'presentation': 'dropdown'},
        ],

        editable=True,
        dropdown={
            'climate': {
                'options': [
                    {'label': 'label {}'.format(i), 'value': i}
                    for i in df['climate'].unique()
                ]
            },
            'city': {
                 'options': [
                    {'label': 'label {}'.format(i), 'value': i}
                    for i in df['city'].unique()
                ]
            }
        }
    ),
    html.Div(id='table-dropdown-container'),
    html.Button(id='button', children='Swap editable columns', n_clicks=0),
])

@app.callback(Output('table-dropdown', 'columns'),
              [Input('button', 'n_clicks')])
def swap_editable(n):
    if not n > 0:
        raise dash.exceptions.PreventUpdate
    if n % 2 == 0:
        return [
            {'id': 'climate', 'name': 'climate', 'presentation': 'dropdown', 'editable': False},
            {'id': 'temperature', 'name': 'temperature'},
            {'id': 'city', 'name': 'city', 'presentation': 'dropdown'},
        ]
    else:
        return [
            {'id': 'climate', 'name': 'climate', 'presentation': 'dropdown'},
            {'id': 'temperature', 'name': 'temperature'},
            {'id': 'city', 'name': 'city', 'presentation': 'dropdown', 'editable': False},
        ]


if __name__ == '__main__':
    app.run_server(debug=True)
```

### PR DESCRIPTION
**Pull request by Marc-Andre-Rivet**
Closes #524. Fixes regression introduced by https://github.com/plotly/dash-table/pull/281.

- When using a label in-place of dropdown component, make sure to resolve the dropdown label instead of just displaying the value.
- Update tests so that labels are different from values, making testing for this error easier
- Additional visual tests

### CODE REVIEW

File: tests/cypress/tests/standalone/readonly_sorting_test.ts [hunk 1]
```diff
@@ -10,15 +10,25 @@ Object.values([AppMode.ReadOnly]).forEach(mode => {
...
-            DashTable.getCell(0, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'Humid'));
-            DashTable.getCell(1, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'Humid'));
-            DashTable.getCell(2, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'Humid'));
-            DashTable.getCell(3, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'Humid'));
+            DashTable.getCell(0, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+            DashTable.getCell(1, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+            DashTable.getCell(2, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+            DashTable.getCell(3, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+
+            DashTable.getCell(0, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
```
Comment (Marc-Andre-Rivet) [inline tests/cypress/tests/standalone/readonly_sorting_test.ts]: also check the readonly column

File: tests/cypress/tests/standalone/readonly_sorting_test.ts [hunk 2]
```diff
@@ -10,15 +10,25 @@ Object.values([AppMode.ReadOnly]).forEach(mode => {
...
-            DashTable.getCell(3, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'Humid'));
+            DashTable.getCell(0, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Wet'));
+            DashTable.getCell(1, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Snowy'));
+            DashTable.getCell(2, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Tropical Beaches'));
+            DashTable.getCell(3, 6).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+
+            DashTable.getCell(0, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Wet'));
+            DashTable.getCell(1, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Snowy'));
+            DashTable.getCell(2, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Tropical Beaches'));
+            DashTable.getCell(3, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
```
Comment (Marc-Andre-Rivet) [inline tests/cypress/tests/standalone/readonly_sorting_test.ts]: also check the readonly column

File: tests/cypress/tests/standalone/readwrite_sorting_test.ts [hunk 3]
```diff
@@ -10,15 +10,25 @@ Object.values(ReadWriteModes).forEach(mode => {
...
-            DashTable.getCell(3, 6).within(() => cy.get('.Select-value-label').should('have.html', 'Humid'));
+            DashTable.getCell(0, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Wet'));
+            DashTable.getCell(1, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Snowy'));
+            DashTable.getCell(2, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Tropical Beaches'));
+            DashTable.getCell(3, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Humid'));
+
+            DashTable.getCell(0, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Wet'));
+            DashTable.getCell(1, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Snowy'));
+            DashTable.getCell(2, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Tropical Beaches'));
+            DashTable.getCell(3, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
```
Comment (Marc-Andre-Rivet) [inline tests/cypress/tests/standalone/readwrite_sorting_test.ts]: also check the readonly column

File: tests/cypress/tests/standalone/readwrite_sorting_test.ts [hunk 4]
```diff
@@ -10,15 +10,25 @@ Object.values(ReadWriteModes).forEach(mode => {
...
-            DashTable.getCell(3, 6).within(() => cy.get('.Select-value-label').should('have.html', 'Humid'));
+            DashTable.getCell(0, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Humid'));
+            DashTable.getCell(1, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Humid'));
+            DashTable.getCell(2, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Humid'));
+            DashTable.getCell(3, 6).within(() => cy.get('.Select-value-label').should('have.html', 'label: Humid'));
+
+            DashTable.getCell(0, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+            DashTable.getCell(1, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+            DashTable.getCell(2, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
+            DashTable.getCell(3, 7).within(() => cy.get('.dash-cell-value').should('have.html', 'label: Humid'));
```
Comment (Marc-Andre-Rivet) [inline tests/cypress/tests/standalone/readwrite_sorting_test.ts]: also check the readonly column

File: tests/visual/percy-storybook/Dropdown.percy.tsx [hunk 5]
```diff
@@ -30,6 +30,48 @@ const columns2 = R.map(
...
+                )
+            },
+            city: {
+                options: R.map(
+                    i => ({ label: `label: ${i}`, value: i }),
+                    ['NYC', 'Montreal', 'Miami']
+                )
+            }
+        }}
+    />)
```
Comment (Marc-Andre-Rivet) [inline tests/visual/percy-storybook/Dropdown.percy.tsx]: visual tests for readonly and editable dropdowns

File: demo/AppMode.ts [hunk 6]
```diff
@@ -56,7 +56,14 @@ function getBaseTableProps(mock: IDataMock) {
...
                 options: ['Humid', 'Wet', 'Snowy', 'Tropical Beaches'].map(i => ({
-                    label: i,
+                    label: `label: ${i}`,
+                    value: i
+                }))
+            },
+            'bbb-readonly': {
+                clearable: true,
+                options: ['Humid', 'Wet', 'Snowy', 'Tropical Beaches'].map(i => ({
+                    label: `label: ${i}`,
```
Comment (Marc-Andre-Rivet) [inline demo/AppMode.ts]: Differentiate between the label and value to catch these differences in the tests.

File: src/dash-table/derived/cell/contents.tsx [hunk 7]
```diff
@@ -26,6 +26,7 @@ const mapRow = R.addIndex<IColumn, JSX.Element>(R.map);
 
 enum CellType {
     Dropdown,
+    DropdownLabel,
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/derived/cell/contents.tsx]: To make it easier to distinguish between the general label case and the dropdown one. Processing is different.

File: tests/cypress/tests/standalone/filtering_test.ts [hunk 8]
```diff
@@ -101,7 +101,7 @@ describe('filter', () => {
         DashTable.getFilterById('ccc').click();
 
         DashTable.getFilterById('bbb').within(() => cy.get('input').should('have.value', 'Tr'));
-        DashTable.getCellById(0, 'bbb-readonly').within(() => cy.get('.dash-cell-value').should('have.html', 'Tropical Beaches'));
+        DashTable.getCellById(0, 'bbb-readonly').within(() => cy.get('.dash-cell-value').should('have.html', 'label: Tropical Beaches'));
```
Comment (Marc-Andre-Rivet) [inline tests/cypress/tests/standalone/filtering_test.ts]: Update tests involving dropdowns so as to expect the `label: ` prefix

File: tests/visual/percy-storybook/Dropdown.percy.tsx (hunk 5 above)
Comment (Marc-Andre-Rivet) [reply tests/visual/percy-storybook/Dropdown.percy.tsx]: Used in conjonction with the updated standalone tests above
