### PR TITLE
Issue 206 - Filter copy/paste

### LINKED ISSUE #206: copying and pasting strings into the `filter` cell doesn't work?

### PR DESCRIPTION
**Pull request by Marc-Andre-Rivet**
Fixes #206 

Allow copy/paste from/to filter columns inputs.

**Note**: Sadly there's no good way to test this through Cypress. The table cell copy could be done because of the way the data is copied and pasted, could be shimmed with some tweaking. There's no clear path here.

### CODE REVIEW

File: src/dash-table/utils/TableClipboardHelper.ts [hunk 1]
```diff
@@ -42,6 +42,12 @@ export default class TableClipboardHelper {
         Clipboard.set(e, value);
     }
 
+    public static clearClipboard() {
+        Clipboard.clear();
+        TableClipboardHelper.lastLocalCopy = [];
+        TableClipboardHelper.localCopyWithoutHeaders = [];
+    }
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/utils/TableClipboardHelper.ts]: Deal with the special table copy/paste code -- reset the previsouly set copies -- will pick up the last copy event normally when doing a paste from filter columns.

File: src/dash-table/components/Filter/Column.tsx [hunk 2]
```diff
@@ -51,6 +52,13 @@ export default class ColumnFilter extends PureComponent<IColumnFilterProps, ISta
             style={style}
         >
             <IsolatedInput
+                onCopy={(e: any) => {
+                    e.stopPropagation();
+                    TableClipboardHelper.clearClipboard();
+                }}
+                onPaste={(e: any) => {
+                    e.stopPropagation();
```
Comment (Marc-Andre-Rivet) [inline src/dash-table/components/Filter/Column.tsx]: prevent copy/paste from being handled by the global table handler
